---

- name: Converge
  hosts: all
  gather_facts: false

  tasks:

    - name: Ping test
      ansible.builtin.ping:

    - name: Test debug
      ansible.builtin.debug:
        var: ansible_host

    - name: "Include molecule-podman"
      ansible.builtin.include_role:
        name: "molecule-podman"
